import 'coffee/extensions/prototype-extensions';
import 'coffee/extensions/set';

import 'coffee/settings'
import 'coffee/constants'
import 'coffee/setup'
import 'coffee/utils'
import 'coffee/plugins'
import 'coffee/tracking'

import 'coffee/mixins/events'

import 'coffee/io/io'
import 'coffee/io/svg'
import 'coffee/io/png'

import 'coffee/uiClasses/font'
import 'coffee/uiClasses/color'

// import 'coffee/lab/lab'
// import 'coffee/lab/analysis'
// import 'coffee/lab/conversions'

import 'coffee/geometry/transformations'
import 'coffee/geometry/posn'
import 'coffee/geometry/point'
import 'coffee/geometry/polynomial'
import 'coffee/geometry/range'
import 'coffee/geometry/bounds'
import 'coffee/geometry/bezier-antlers'
import 'coffee/geometry/path-points'
import 'coffee/geometry/points-list'
import 'coffee/geometry/points-segment'
import 'coffee/geometry/line-segment'
import 'coffee/geometry/ray'
import 'coffee/geometry/cubic-bezier-line-segment'
import 'coffee/geometry/monsvg'
import 'coffee/geometry/hover-target'
import 'coffee/geometry/line'
import 'coffee/geometry/rectangle'
import 'coffee/geometry/circle'
import 'coffee/geometry/ellipse'
import 'coffee/geometry/polygon'
import 'coffee/geometry/polyline'
import 'coffee/geometry/path'
import 'coffee/geometry/text'
import 'coffee/geometry/text-editable'
import 'coffee/geometry/tspan'
import 'coffee/geometry/pathfinder'

import 'coffee/files/file'
import 'coffee/files/local-file'
import 'coffee/files/permalink-file'
import 'coffee/files/dropbox-file'
import 'coffee/files/demo-files'

import 'coffee/archive/archive'
import 'coffee/archive/event'
import 'coffee/archive/map-event'
import 'coffee/archive/attr-event'
import 'coffee/archive/zindex-event'
import 'coffee/archive/existence-event'
import 'coffee/archive/point-existence-event'

import 'coffee/dom/dom'

import 'coffee/ui/ui'
import 'coffee/ui/logo'
import 'coffee/ui/state'
import 'coffee/ui/selection'
import 'coffee/ui/selection-macros'
import 'coffee/ui/window'
import 'coffee/ui/clipboard'
import 'coffee/ui/error-reporting'
import 'coffee/ui/afk'
import 'coffee/ui/topui'
import 'coffee/ui/tooltips'
import 'coffee/ui/swatch'
import 'coffee/ui/swatch-duo'
import 'coffee/ui/snapping'
import 'coffee/ui/canvas'
import 'coffee/ui/cursor-tracking'
import 'coffee/ui/drag-select'
import 'coffee/ui/transformer'
import 'coffee/ui/hotkeys'
import 'coffee/ui/gallery'
import 'coffee/ui/browser'

import 'coffee/controls/control'
import 'coffee/controls/dropdown'
import 'coffee/controls/number-box'
import 'coffee/controls/text-box'
import 'coffee/controls/slider'

import 'coffee/menu/menu'
import 'coffee/menu/item'
import 'coffee/menu/file-menu'
import 'coffee/menu/edit-menu'
import 'coffee/menu/view-menu'
import 'coffee/menu/about-menu'
import 'coffee/menu/login-menu'
import 'coffee/menu/register-menu'
import 'coffee/menu/geometry-menu'
import 'coffee/menu/account-menu'
import 'coffee/menu/share-menu'
import 'coffee/menu/embed-menu'
import 'coffee/menu/filename-item'
import 'coffee/menu/save-item'
import 'coffee/menu/new-item'
import 'coffee/menu/logout-item'
import 'coffee/menu/open-item'
import 'coffee/menu/dropbox-item'
import 'coffee/menu/download-item'
import 'coffee/menu/z-index-items'

import 'coffee/utilities/utility'
import 'coffee/utilities/color-picker'
import 'coffee/utilities/current-swatches'
import 'coffee/utilities/transform'
import 'coffee/utilities/stroke-width'
import 'coffee/utilities/typography'
import 'coffee/utilities/archive'

import 'coffee/tools/tool'
import 'coffee/tools/cursor'
import 'coffee/tools/paw'
import 'coffee/tools/pen'
import 'coffee/tools/crayon'
import 'coffee/tools/line'
import 'coffee/tools/arbitrary-shape'
import 'coffee/tools/ellipse'
import 'coffee/tools/rectangle'
import 'coffee/tools/type'
import 'coffee/tools/rotate'
import 'coffee/tools/zoom'
import 'coffee/tools/eyedropper'

import 'coffee/services/services'
import 'coffee/services/local'
import 'coffee/services/permalink'
import 'coffee/services/dropbox'

import 'coffee/annotations/annotations'
import 'coffee/annotations/grid'

import 'coffee/user/account'

import 'coffee/browser/url'
import 'coffee/browser/browser-file'
