import 'script/extensions/prototype-extensions';
import 'script/extensions/set';

import 'script/settings'
import 'script/constants'
import 'script/setup'
import 'script/utils'
import 'script/plugins'
import 'script/tracking'

import 'script/mixins/events'

import 'script/io/io'
import 'script/io/svg'
import 'script/io/png'

import 'script/uiClasses/font'
import 'script/uiClasses/color'

import 'script/lab/lab'
// import 'script/lab/analysis'
import 'script/lab/conversions'

import 'script/geometry/transformations'
import 'script/geometry/posn'
import 'script/geometry/point'
import 'script/geometry/polynomial'
import 'script/geometry/range'
import 'script/geometry/bounds'
import 'script/geometry/bezier-antlers'
import 'script/geometry/path-points'
import 'script/geometry/points-list'
import 'script/geometry/points-segment'
import 'script/geometry/line-segment'
import 'script/geometry/ray'
import 'script/geometry/cubic-bezier-line-segment'
import 'script/geometry/monsvg'
import 'script/geometry/hover-target'
import 'script/geometry/line'
import 'script/geometry/rectangle'
import 'script/geometry/circle'
import 'script/geometry/ellipse'
import 'script/geometry/polygon'
import 'script/geometry/polyline'
import 'script/geometry/path'
import 'script/geometry/text'
import 'script/geometry/text-editable'
import 'script/geometry/tspan'
import 'script/geometry/pathfinder'

import 'script/files/file'
import 'script/files/local-file'
import 'script/files/permalink-file'
import 'script/files/dropbox-file'
import 'script/files/demo-files'

import 'script/archive/archive'
import 'script/archive/event'
import 'script/archive/map-event'
import 'script/archive/attr-event'
import 'script/archive/zindex-event'
import 'script/archive/existence-event'
import 'script/archive/point-existence-event'

import 'script/dom/dom'

import 'script/ui/ui'
import 'script/ui/logo'
import 'script/ui/state'
import 'script/ui/selection'
import 'script/ui/selection-macros'
import 'script/ui/window'
import 'script/ui/clipboard'
import 'script/ui/error-reporting'
import 'script/ui/afk'
import 'script/ui/topui'
import 'script/ui/tooltips'
import 'script/ui/swatch'
import 'script/ui/swatch-duo'
import 'script/ui/snapping'
import 'script/ui/canvas'
import 'script/ui/cursor-tracking'
import 'script/ui/drag-select'
import 'script/ui/transformer'
import 'script/ui/hotkeys'
import 'script/ui/gallery'
import 'script/ui/browser'

import 'script/controls/control'
import 'script/controls/dropdown'
import 'script/controls/number-box'
import 'script/controls/text-box'
import 'script/controls/slider'

import 'script/menu/menu'
import 'script/menu/item'
import 'script/menu/file-menu'
import 'script/menu/edit-menu'
import 'script/menu/view-menu'
import 'script/menu/about-menu'
import 'script/menu/login-menu'
import 'script/menu/register-menu'
import 'script/menu/geometry-menu'
import 'script/menu/account-menu'
import 'script/menu/share-menu'
import 'script/menu/embed-menu'
import 'script/menu/filename-item'
import 'script/menu/save-item'
import 'script/menu/new-item'
import 'script/menu/logout-item'
import 'script/menu/open-item'
import 'script/menu/dropbox-item'
import 'script/menu/download-item'
import 'script/menu/z-index-items'

import 'script/utilities/utility'
import 'script/utilities/color-picker'
import 'script/utilities/current-swatches'
import 'script/utilities/transform'
import 'script/utilities/stroke-width'
import 'script/utilities/typography'
import 'script/utilities/archive'

import 'script/tools/tool'
import 'script/tools/cursor'
import 'script/tools/paw'
import 'script/tools/pen'
import 'script/tools/crayon'
import 'script/tools/line'
import 'script/tools/arbitrary-shape'
import 'script/tools/ellipse'
import 'script/tools/rectangle'
import 'script/tools/type'
import 'script/tools/rotate'
import 'script/tools/zoom'
import 'script/tools/eyedropper'

import 'script/services/services'
import 'script/services/local'
import 'script/services/permalink'
import 'script/services/dropbox'

import 'script/annotations/annotations'
import 'script/annotations/grid'

import 'script/user/account'

import 'script/browser/url'
import 'script/browser/browser-file'
